# Generated by Django 2.0.1 on 2018-02-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('teacher', models.BooleanField(default=False)),
                ('phone_number', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
