# Generated by Django 2.0.1 on 2018-02-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20180203_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.FileField(upload_to='teacher/image/%Y/%m/%d'),
        ),
    ]
