# Generated by Django 2.0.1 on 2018-02-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
