# Generated by Django 2.0.1 on 2018-02-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20180203_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.FileField(upload_to='student/image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(upload_to='student/resuem/%Y/%m/%d'),
        ),
    ]
