# Generated by Django 2.0.1 on 2018-02-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20180205_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('author_name', models.CharField(max_length=300)),
                ('publication', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
